import React from 'react';
import type { StoryObj } from '@storybook/react';
import { CheckboxProps } from '../../components';
declare const meta: {
    title: string;
    component: React.ForwardRefExoticComponent<CheckboxProps & React.RefAttributes<import("../../components").RadioRef>>;
    tags: string[];
    argTypes: Partial<import("@storybook/types").ArgTypes<CheckboxProps>> | undefined;
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const Root: Story;
export declare const ContainedPlus: Story;
export declare const ContainedCheckmark: Story;
export declare const ContainedCross: Story;
export declare const ContainedMinus: Story;
export declare const OutlinedPlus: Story;
export declare const OutlinedCheckmark: Story;
export declare const OutlinedMinus: Story;
