import { merge } from 'lodash';
import Alert from '../../theme/components/Alert';
import Autocomplete from '../../theme/components/Autocomplete';
import Avatar from '../../theme/components/Avatar';
import AvatarGroup from '../../theme/components/AvatarGroup';
import Backdrop from '../../theme/components/Backdrop';
import Badge from '../../theme/components/Badge';
import Box from '../../theme/components/Box';
import Button from '../../theme/components/Button';
import ButtonGroup from '../../theme/components/ButtonGroup';
import Checkbox from '../../theme/components/Checkbox';
import Chip from '../../theme/components/Chip';
import CircularLoading from '../../theme/components/CircularLoading';
import Divider from '../../theme/components/Divider';
import Drawer from '../../theme/components/Drawer';
import Icon from '../../theme/components/Icon';
import Input from '../../theme/components/Input';
import Link from '../../theme/components/Link';
import Modal from '../../theme/components/Modal';
import Paper from '../../theme/components/Paper';
import Popover from '../../theme/components/Popover';
import Portal from '../../theme/components/Portal';
import ProgressBar from '../../theme/components/ProgressBar';
import Radio from '../../theme/components/Radio';
import Select from '../../theme/components/Select';
import Slider from '../../theme/components/Slider';
import Switch from '../../theme/components/Switch';
import TextArea from '../../theme/components/TextArea';
import Tooltip from '../../theme/components/Tooltip';
import Typography from '../../theme/components/Typography';
var themeComponents = function (theme) { return merge({}, Alert, Autocomplete, Avatar(theme), AvatarGroup, Backdrop(theme), Badge, Box(theme), Button(theme), ButtonGroup(theme), Checkbox, Chip, CircularLoading, Divider, Drawer, Icon, Input, Link, Modal(theme), Paper(theme), Popover(theme), Portal, ProgressBar, Radio, Select, Slider, Switch, TextArea, Tooltip, Typography); };
export default themeComponents;
